name: Webitech

on :
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      name: Afficher Greeting dans le job 1
      run: |
        echo "Ma variable a la valeur ${{vars.PRENOM}}"
          
