name: Mon Workflow

on:
  push:
    branches:
      - main

env:
  MY_VARIABLE: "Valeur de ma variable globale"

jobs:
  mon_job:
    runs-on: ubuntu-latest

    steps:
    - name: Étape 1 - Afficher la variable globale
      run: echo "La variable globale MY_VARIABLE a la valeur $MY_VARIABLE"
